from calendar import error
from flask import Flask, render_template, request
import requests
import matplotlib.pyplot as plt
import numpy as np
import io
import base64
from datetime import datetime
import matplotlib.dates as mdates
from matplotlib.ticker import MultipleLocator

app = Flask(__name__)

# API KEY : SSOF7SE9YKYKXX51

""" use only when API is down """
info_exemple = {
    "Symbol": "IBM",
    "AssetType": "Common Stock",
    "Name": "International Business Machines",
    "Description": "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
    "CIK": "51143",
    "Exchange": "NYSE",
    "Currency": "USD",
    "Country": "USA",
    "Sector": "TECHNOLOGY",
    "Industry": "COMPUTER & OFFICE EQUIPMENT",
    "Address": "1 NEW ORCHARD ROAD, ARMONK, NY, US",
    "OfficialSite": "https://www.ibm.com",
    "FiscalYearEnd": "December",
    "LatestQuarter": "2024-09-30",
    "MarketCapitalization": "192557318000",
    "EBITDA": "11951000000",
    "PERatio": "30.4",
    "PEGRatio": "6.9",
    "BookValue": "26.44",
    "DividendPerShare": "6.66",
    "DividendYield": "0.0321",
    "EPS": "6.85",
    "RevenuePerShareTTM": "68.11",
    "ProfitMargin": "0.102",
    "OperatingMarginTTM": "-0.0408",
    "ReturnOnAssetsTTM": "0.0344",
    "ReturnOnEquityTTM": "0.267",
    "RevenueTTM": "62579999000",
    "GrossProfitTTM": "32688000000",
    "DilutedEPSTTM": "6.85",
    "QuarterlyEarningsGrowthYOY": "0.141",
    "QuarterlyRevenueGrowthYOY": "0.015",
    "AnalystTargetPrice": "213.65",
    "AnalystRatingStrongBuy": "4",
    "AnalystRatingBuy": "5",
    "AnalystRatingHold": "10",
    "AnalystRatingSell": "3",
    "AnalystRatingStrongSell": "0",
    "TrailingPE": "30.4",
    "ForwardPE": "19.3",
    "PriceToSalesRatioTTM": "3.077",
    "PriceToBookRatio": "7.88",
    "EVToRevenue": "3.819",
    "EVToEBITDA": "18.89",
    "Beta": "0.697",
    "52WeekHigh": "237.37",
    "52WeekLow": "141.32",
    "50DayMovingAverage": "216.72",
    "200DayMovingAverage": "190.28",
    "SharesOutstanding": "924645000",
    "DividendDate": "2024-09-10",
    "ExDividendDate": "2024-11-12"
}
example = {
    "bestMatches": [
        {
            "1. symbol": "TSCO.LON",
            "2. name": "Tesco PLC",
            "3. type": "Equity",
            "4. region": "United Kingdom",
            "5. marketOpen": "08:00",
            "6. marketClose": "16:30",
            "7. timezone": "UTC+01",
            "8. currency": "GBX",
            "9. matchScore": "0.7273"
        },
        {
            "1. symbol": "TSCDF",
            "2. name": "Tesco plc",
            "3. type": "Equity",
            "4. region": "United States",
            "5. marketOpen": "09:30",
            "6. marketClose": "16:00",
            "7. timezone": "UTC-04",
            "8. currency": "USD",
            "9. matchScore": "0.7143"
        },
        {
            "1. symbol": "TSCDY",
            "2. name": "Tesco plc",
            "3. type": "Equity",
            "4. region": "United States",
            "5. marketOpen": "09:30",
            "6. marketClose": "16:00",
            "7. timezone": "UTC-04",
            "8. currency": "USD",
            "9. matchScore": "0.7143"
        },
        {
            "1. symbol": "TCO2.FRK",
            "2. name": "TESCO PLC ADR/1 LS-05",
            "3. type": "Equity",
            "4. region": "Frankfurt",
            "5. marketOpen": "08:00",
            "6. marketClose": "20:00",
            "7. timezone": "UTC+02",
            "8. currency": "EUR",
            "9. matchScore": "0.5455"
        },
        {
            "1. symbol": "TCO0.FRK",
            "2. name": "TESCO PLC LS-0633333",
            "3. type": "Equity",
            "4. region": "Frankfurt",
            "5. marketOpen": "08:00",
            "6. marketClose": "20:00",
            "7. timezone": "UTC+02",
            "8. currency": "EUR",
            "9. matchScore": "0.5455"
        }
    ]
}
data_exemple = {
    "Meta Data": {
        "1. Information": "Intraday (5min) open, high, low, close prices and volume",
        "2. Symbol": "IBM",
        "3. Last Refreshed": "2024-11-01 19:55:00",
        "4. Interval": "5min",
        "5. Output Size": "Compact",
        "6. Time Zone": "US/Eastern"
    },
    "Time Series (5min)": {
        "2024-11-01 19:55:00": {
            "1. open": "208.1700",
            "2. high": "208.3500",
            "3. low": "208.1000",
            "4. close": "208.1800",
            "5. volume": "110"
        },
        "2024-11-01 19:50:00": {
            "1. open": "208.0200",
            "2. high": "208.0200",
            "3. low": "208.0200",
            "4. close": "208.0200",
            "5. volume": "5"
        },
        "2024-11-01 19:30:00": {
            "1. open": "208.7000",
            "2. high": "208.7000",
            "3. low": "208.7000",
            "4. close": "208.7000",
            "5. volume": "1"
        },
        "2024-11-01 19:25:00": {
            "1. open": "208.0000",
            "2. high": "208.0000",
            "3. low": "207.8000",
            "4. close": "207.8000",
            "5. volume": "4"
        },
        "2024-11-01 19:15:00": {
            "1. open": "208.2500",
            "2. high": "208.2500",
            "3. low": "207.8000",
            "4. close": "207.8000",
            "5. volume": "12"
        },
        "2024-11-01 19:10:00": {
            "1. open": "208.1700",
            "2. high": "208.2500",
            "3. low": "208.1700",
            "4. close": "208.2500",
            "5. volume": "23"
        },
        "2024-11-01 19:05:00": {
            "1. open": "208.1700",
            "2. high": "208.1800",
            "3. low": "208.1700",
            "4. close": "208.1800",
            "5. volume": "9"
        },
        "2024-11-01 19:00:00": {
            "1. open": "208.2500",
            "2. high": "208.2500",
            "3. low": "208.2500",
            "4. close": "208.2500",
            "5. volume": "490600"
        },
        "2024-11-01 18:55:00": {
            "1. open": "207.8000",
            "2. high": "208.1800",
            "3. low": "207.8000",
            "4. close": "207.9100",
            "5. volume": "36"
        },
        "2024-11-01 18:45:00": {
            "1. open": "209.1200",
            "2. high": "209.1200",
            "3. low": "208.6988",
            "4. close": "208.6988",
            "5. volume": "2"
        },
        "2024-11-01 18:40:00": {
            "1. open": "208.1800",
            "2. high": "208.1800",
            "3. low": "208.1800",
            "4. close": "208.1800",
            "5. volume": "1"
        },
        "2024-11-01 18:35:00": {
            "1. open": "208.1700",
            "2. high": "208.1800",
            "3. low": "208.1700",
            "4. close": "208.1800",
            "5. volume": "30"
        },
        "2024-11-01 18:30:00": {
            "1. open": "208.2500",
            "2. high": "208.2500",
            "3. low": "208.2500",
            "4. close": "208.2500",
            "5. volume": "490600"
        },
        "2024-11-01 18:20:00": {
            "1. open": "208.0000",
            "2. high": "208.1800",
            "3. low": "208.0000",
            "4. close": "208.1800",
            "5. volume": "5"
        },
        "2024-11-01 18:10:00": {
            "1. open": "208.7000",
            "2. high": "208.7000",
            "3. low": "208.1900",
            "4. close": "208.1900",
            "5. volume": "25762"
        },
        "2024-11-01 18:05:00": {
            "1. open": "208.7000",
            "2. high": "208.7000",
            "3. low": "208.7000",
            "4. close": "208.7000",
            "5. volume": "2"
        },
        "2024-11-01 17:55:00": {
            "1. open": "207.8360",
            "2. high": "208.7000",
            "3. low": "207.8360",
            "4. close": "208.7000",
            "5. volume": "79"
        },
        "2024-11-01 17:50:00": {
            "1. open": "208.7000",
            "2. high": "208.7000",
            "3. low": "208.7000",
            "4. close": "208.7000",
            "5. volume": "3"
        },
        "2024-11-01 17:45:00": {
            "1. open": "207.8940",
            "2. high": "208.2500",
            "3. low": "207.8940",
            "4. close": "208.2500",
            "5. volume": "36"
        },
        "2024-11-01 17:35:00": {
            "1. open": "208.7000",
            "2. high": "208.7000",
            "3. low": "208.0400",
            "4. close": "208.0400",
            "5. volume": "158"
        },
        "2024-11-01 17:25:00": {
            "1. open": "208.2500",
            "2. high": "208.2500",
            "3. low": "208.2500",
            "4. close": "208.2500",
            "5. volume": "80"
        },
        "2024-11-01 17:20:00": {
            "1. open": "208.2500",
            "2. high": "208.2600",
            "3. low": "208.2200",
            "4. close": "208.2600",
            "5. volume": "326"
        },
        "2024-11-01 17:15:00": {
            "1. open": "208.0400",
            "2. high": "208.2500",
            "3. low": "207.9750",
            "4. close": "207.9750",
            "5. volume": "4781"
        },
        "2024-11-01 17:10:00": {
            "1. open": "208.0600",
            "2. high": "208.2500",
            "3. low": "208.0600",
            "4. close": "208.2500",
            "5. volume": "25"
        },
        "2024-11-01 17:05:00": {
            "1. open": "208.2000",
            "2. high": "208.2400",
            "3. low": "208.2000",
            "4. close": "208.2400",
            "5. volume": "14"
        },
        "2024-11-01 16:55:00": {
            "1. open": "208.4900",
            "2. high": "208.4900",
            "3. low": "208.0000",
            "4. close": "208.0300",
            "5. volume": "735"
        },
        "2024-11-01 16:50:00": {
            "1. open": "208.2500",
            "2. high": "208.2500",
            "3. low": "208.2500",
            "4. close": "208.2500",
            "5. volume": "1017"
        },
        "2024-11-01 16:45:00": {
            "1. open": "208.2500",
            "2. high": "208.4200",
            "3. low": "208.0100",
            "4. close": "208.0100",
            "5. volume": "329"
        },
        "2024-11-01 16:40:00": {
            "1. open": "208.4100",
            "2. high": "208.5000",
            "3. low": "208.3900",
            "4. close": "208.4200",
            "5. volume": "100"
        },
        "2024-11-01 16:35:00": {
            "1. open": "208.4100",
            "2. high": "208.4100",
            "3. low": "207.3000",
            "4. close": "207.3000",
            "5. volume": "11"
        },
        "2024-11-01 16:30:00": {
            "1. open": "208.9900",
            "2. high": "208.9900",
            "3. low": "208.4100",
            "4. close": "208.4100",
            "5. volume": "12"
        },
        "2024-11-01 16:25:00": {
            "1. open": "208.5700",
            "2. high": "208.6000",
            "3. low": "208.3300",
            "4. close": "208.4100",
            "5. volume": "154"
        },
        "2024-11-01 16:20:00": {
            "1. open": "208.2500",
            "2. high": "208.4000",
            "3. low": "208.2500",
            "4. close": "208.4000",
            "5. volume": "12632"
        },
        "2024-11-01 16:15:00": {
            "1. open": "208.2500",
            "2. high": "208.2500",
            "3. low": "207.3000",
            "4. close": "207.3000",
            "5. volume": "1905"
        },
        "2024-11-01 16:10:00": {
            "1. open": "208.2500",
            "2. high": "209.2700",
            "3. low": "208.2500",
            "4. close": "208.2500",
            "5. volume": "496779"
        },
        "2024-11-01 16:05:00": {
            "1. open": "208.2000",
            "2. high": "208.5605",
            "3. low": "207.3000",
            "4. close": "208.4000",
            "5. volume": "1479"
        },
        "2024-11-01 16:00:00": {
            "1. open": "208.2400",
            "2. high": "209.8900",
            "3. low": "208.2200",
            "4. close": "209.8900",
            "5. volume": "1250328"
        },
        "2024-11-01 15:55:00": {
            "1. open": "208.4700",
            "2. high": "208.5100",
            "3. low": "208.2000",
            "4. close": "208.2300",
            "5. volume": "233480"
        },
        "2024-11-01 15:50:00": {
            "1. open": "208.0600",
            "2. high": "208.5000",
            "3. low": "207.9750",
            "4. close": "208.4900",
            "5. volume": "119242"
        },
        "2024-11-01 15:45:00": {
            "1. open": "208.0900",
            "2. high": "208.1300",
            "3. low": "208.0400",
            "4. close": "208.0672",
            "5. volume": "44029"
        },
        "2024-11-01 15:40:00": {
            "1. open": "208.0799",
            "2. high": "208.2900",
            "3. low": "208.0200",
            "4. close": "208.1200",
            "5. volume": "44083"
        },
        "2024-11-01 15:35:00": {
            "1. open": "208.2400",
            "2. high": "208.2700",
            "3. low": "208.0000",
            "4. close": "208.0400",
            "5. volume": "40293"
        },
        "2024-11-01 15:30:00": {
            "1. open": "208.4500",
            "2. high": "208.4700",
            "3. low": "208.1550",
            "4. close": "208.2350",
            "5. volume": "37823"
        },
        "2024-11-01 15:25:00": {
            "1. open": "208.9700",
            "2. high": "208.9879",
            "3. low": "208.4266",
            "4. close": "208.4266",
            "5. volume": "49458"
        },
        "2024-11-01 15:20:00": {
            "1. open": "209.0600",
            "2. high": "209.1500",
            "3. low": "208.9600",
            "4. close": "208.9600",
            "5. volume": "44731"
        },
        "2024-11-01 15:15:00": {
            "1. open": "208.8600",
            "2. high": "209.0700",
            "3. low": "208.8500",
            "4. close": "209.0583",
            "5. volume": "23707"
        },
        "2024-11-01 15:10:00": {
            "1. open": "208.8050",
            "2. high": "208.9200",
            "3. low": "208.7400",
            "4. close": "208.8900",
            "5. volume": "24758"
        },
        "2024-11-01 15:05:00": {
            "1. open": "208.2500",
            "2. high": "208.8100",
            "3. low": "208.2500",
            "4. close": "208.8050",
            "5. volume": "32614"
        },
        "2024-11-01 15:00:00": {
            "1. open": "208.4400",
            "2. high": "208.5100",
            "3. low": "208.1300",
            "4. close": "208.2300",
            "5. volume": "43087"
        },
        "2024-11-01 14:55:00": {
            "1. open": "208.4200",
            "2. high": "208.5400",
            "3. low": "208.4000",
            "4. close": "208.4400",
            "5. volume": "30347"
        },
        "2024-11-01 14:50:00": {
            "1. open": "208.6400",
            "2. high": "208.6800",
            "3. low": "208.4000",
            "4. close": "208.4600",
            "5. volume": "29851"
        },
        "2024-11-01 14:45:00": {
            "1. open": "208.6100",
            "2. high": "208.7500",
            "3. low": "208.5800",
            "4. close": "208.6300",
            "5. volume": "32489"
        },
        "2024-11-01 14:40:00": {
            "1. open": "208.5300",
            "2. high": "208.6600",
            "3. low": "208.5200",
            "4. close": "208.6200",
            "5. volume": "26885"
        },
        "2024-11-01 14:35:00": {
            "1. open": "208.2000",
            "2. high": "208.5400",
            "3. low": "208.1650",
            "4. close": "208.5400",
            "5. volume": "15117"
        },
        "2024-11-01 14:30:00": {
            "1. open": "208.4400",
            "2. high": "208.4630",
            "3. low": "208.1900",
            "4. close": "208.2100",
            "5. volume": "26560"
        },
        "2024-11-01 14:25:00": {
            "1. open": "208.3150",
            "2. high": "208.5100",
            "3. low": "208.2300",
            "4. close": "208.4300",
            "5. volume": "56182"
        },
        "2024-11-01 14:20:00": {
            "1. open": "208.2200",
            "2. high": "208.3600",
            "3. low": "208.0900",
            "4. close": "208.3100",
            "5. volume": "28797"
        },
        "2024-11-01 14:15:00": {
            "1. open": "208.2800",
            "2. high": "208.3300",
            "3. low": "208.1500",
            "4. close": "208.2300",
            "5. volume": "10260"
        },
        "2024-11-01 14:10:00": {
            "1. open": "208.2650",
            "2. high": "208.3050",
            "3. low": "208.1700",
            "4. close": "208.2700",
            "5. volume": "11567"
        },
        "2024-11-01 14:05:00": {
            "1. open": "208.4900",
            "2. high": "208.5700",
            "3. low": "208.2300",
            "4. close": "208.3000",
            "5. volume": "15610"
        },
        "2024-11-01 14:00:00": {
            "1. open": "208.1400",
            "2. high": "208.4823",
            "3. low": "208.0900",
            "4. close": "208.4823",
            "5. volume": "21973"
        },
        "2024-11-01 13:55:00": {
            "1. open": "208.3700",
            "2. high": "208.3950",
            "3. low": "208.1500",
            "4. close": "208.1800",
            "5. volume": "20360"
        },
        "2024-11-01 13:50:00": {
            "1. open": "208.1802",
            "2. high": "208.4700",
            "3. low": "208.1800",
            "4. close": "208.3900",
            "5. volume": "22511"
        },
        "2024-11-01 13:45:00": {
            "1. open": "208.3800",
            "2. high": "208.5000",
            "3. low": "208.2400",
            "4. close": "208.2400",
            "5. volume": "32978"
        },
        "2024-11-01 13:40:00": {
            "1. open": "208.6600",
            "2. high": "208.7200",
            "3. low": "208.4000",
            "4. close": "208.4000",
            "5. volume": "17699"
        },
        "2024-11-01 13:35:00": {
            "1. open": "209.1400",
            "2. high": "209.1400",
            "3. low": "208.7300",
            "4. close": "208.7550",
            "5. volume": "18694"
        },
        "2024-11-01 13:30:00": {
            "1. open": "209.6200",
            "2. high": "209.6200",
            "3. low": "209.1415",
            "4. close": "209.1415",
            "5. volume": "14133"
        },
        "2024-11-01 13:25:00": {
            "1. open": "209.5400",
            "2. high": "209.7200",
            "3. low": "209.5400",
            "4. close": "209.5900",
            "5. volume": "17963"
        },
        "2024-11-01 13:20:00": {
            "1. open": "209.2600",
            "2. high": "209.6100",
            "3. low": "209.2300",
            "4. close": "209.5600",
            "5. volume": "22944"
        },
        "2024-11-01 13:15:00": {
            "1. open": "209.0200",
            "2. high": "209.3100",
            "3. low": "209.0200",
            "4. close": "209.3100",
            "5. volume": "18543"
        },
        "2024-11-01 13:10:00": {
            "1. open": "208.8600",
            "2. high": "209.0500",
            "3. low": "208.7318",
            "4. close": "209.0300",
            "5. volume": "18028"
        },
        "2024-11-01 13:05:00": {
            "1. open": "208.9850",
            "2. high": "209.0000",
            "3. low": "208.8100",
            "4. close": "208.8700",
            "5. volume": "14476"
        },
        "2024-11-01 13:00:00": {
            "1. open": "208.9300",
            "2. high": "209.0400",
            "3. low": "208.9300",
            "4. close": "208.9700",
            "5. volume": "11047"
        },
        "2024-11-01 12:55:00": {
            "1. open": "208.9750",
            "2. high": "208.9900",
            "3. low": "208.6950",
            "4. close": "208.8800",
            "5. volume": "25606"
        },
        "2024-11-01 12:50:00": {
            "1. open": "208.9800",
            "2. high": "209.0400",
            "3. low": "208.9500",
            "4. close": "209.0100",
            "5. volume": "15702"
        },
        "2024-11-01 12:45:00": {
            "1. open": "208.9600",
            "2. high": "209.0800",
            "3. low": "208.8800",
            "4. close": "208.9800",
            "5. volume": "21849"
        },
        "2024-11-01 12:40:00": {
            "1. open": "209.4300",
            "2. high": "209.4300",
            "3. low": "208.9500",
            "4. close": "208.9900",
            "5. volume": "17517"
        },
        "2024-11-01 12:35:00": {
            "1. open": "209.3900",
            "2. high": "209.4700",
            "3. low": "209.3350",
            "4. close": "209.4350",
            "5. volume": "13551"
        },
        "2024-11-01 12:30:00": {
            "1. open": "209.0900",
            "2. high": "209.4800",
            "3. low": "209.0900",
            "4. close": "209.4200",
            "5. volume": "16540"
        },
        "2024-11-01 12:25:00": {
            "1. open": "209.5100",
            "2. high": "209.5150",
            "3. low": "209.1000",
            "4. close": "209.1282",
            "5. volume": "19532"
        },
        "2024-11-01 12:20:00": {
            "1. open": "209.5300",
            "2. high": "209.5600",
            "3. low": "209.3800",
            "4. close": "209.5050",
            "5. volume": "27643"
        },
        "2024-11-01 12:15:00": {
            "1. open": "209.5100",
            "2. high": "209.6200",
            "3. low": "209.4800",
            "4. close": "209.5000",
            "5. volume": "14847"
        },
        "2024-11-01 12:10:00": {
            "1. open": "209.8050",
            "2. high": "209.8150",
            "3. low": "209.4700",
            "4. close": "209.5162",
            "5. volume": "23521"
        },
        "2024-11-01 12:05:00": {
            "1. open": "209.7050",
            "2. high": "209.8400",
            "3. low": "209.7000",
            "4. close": "209.7900",
            "5. volume": "17525"
        },
        "2024-11-01 12:00:00": {
            "1. open": "209.3875",
            "2. high": "209.8000",
            "3. low": "209.3875",
            "4. close": "209.7100",
            "5. volume": "28258"
        },
        "2024-11-01 11:55:00": {
            "1. open": "209.5200",
            "2. high": "209.5400",
            "3. low": "209.3650",
            "4. close": "209.4236",
            "5. volume": "27959"
        },
        "2024-11-01 11:50:00": {
            "1. open": "209.7850",
            "2. high": "209.7850",
            "3. low": "209.4400",
            "4. close": "209.5400",
            "5. volume": "25595"
        },
        "2024-11-01 11:45:00": {
            "1. open": "209.5800",
            "2. high": "209.8300",
            "3. low": "209.5500",
            "4. close": "209.8100",
            "5. volume": "24417"
        },
        "2024-11-01 11:40:00": {
            "1. open": "209.6350",
            "2. high": "209.7500",
            "3. low": "209.5130",
            "4. close": "209.5550",
            "5. volume": "21677"
        },
        "2024-11-01 11:35:00": {
            "1. open": "209.6600",
            "2. high": "209.6800",
            "3. low": "209.5550",
            "4. close": "209.6600",
            "5. volume": "23310"
        },
        "2024-11-01 11:30:00": {
            "1. open": "209.4600",
            "2. high": "209.7100",
            "3. low": "209.4200",
            "4. close": "209.7100",
            "5. volume": "24217"
        },
        "2024-11-01 11:25:00": {
            "1. open": "209.2100",
            "2. high": "209.4600",
            "3. low": "209.1950",
            "4. close": "209.4400",
            "5. volume": "18187"
        },
        "2024-11-01 11:20:00": {
            "1. open": "209.3400",
            "2. high": "209.3750",
            "3. low": "209.1100",
            "4. close": "209.2309",
            "5. volume": "21237"
        },
        "2024-11-01 11:15:00": {
            "1. open": "209.6100",
            "2. high": "209.6400",
            "3. low": "209.2750",
            "4. close": "209.3700",
            "5. volume": "18205"
        },
        "2024-11-01 11:10:00": {
            "1. open": "209.5000",
            "2. high": "209.6400",
            "3. low": "209.5000",
            "4. close": "209.6232",
            "5. volume": "17934"
        },
        "2024-11-01 11:05:00": {
            "1. open": "209.4100",
            "2. high": "209.5000",
            "3. low": "209.2800",
            "4. close": "209.3800",
            "5. volume": "28924"
        },
        "2024-11-01 11:00:00": {
            "1. open": "209.2101",
            "2. high": "209.4500",
            "3. low": "209.2101",
            "4. close": "209.3800",
            "5. volume": "22941"
        },
        "2024-11-01 10:55:00": {
            "1. open": "208.9399",
            "2. high": "209.3000",
            "3. low": "208.8000",
            "4. close": "209.2600",
            "5. volume": "16203"
        },
        "2024-11-01 10:50:00": {
            "1. open": "208.8499",
            "2. high": "208.9850",
            "3. low": "208.6100",
            "4. close": "208.8900",
            "5. volume": "18135"
        },
        "2024-11-01 10:45:00": {
            "1. open": "208.6400",
            "2. high": "208.7400",
            "3. low": "208.4500",
            "4. close": "208.7300",
            "5. volume": "24691"
        }
    }
}



@app.route('/', methods=['GET', 'POST'])
def hello_world():  # put application's code here

    """data to begin with nothing on page"""
    x = []
    y = []
    error = ''
    data = ''
    search_symbol = ''
    selected_symbol = ''
    present_symbol = ''
    plot_url = ''
    info = ''

    """first call when searching"""
    api_key = 'SSOF7SE9YKYKXX51'
    search_symbol = request.form.get('search_symbol')
    url_search = f'https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords={search_symbol}&apikey={api_key}'
    r_search = requests.get(url_search)
    symbols = r_search.json()
    # symbols = example

    if symbols:
        selected_symbol = request.form.get('selected_symbol')
        url_symbol = f'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol={selected_symbol}&interval=5min&apikey={api_key}'
        r_symbol = requests.get(url_symbol)
        data = r_symbol.json()
        # data = data_exemple
        # print(list(data.keys()))
    else:
        error = 'Seems to be an error with the API' 

    if symbols and data and selected_symbol:

        url_info = f'https://www.alphavantage.co/query?function=OVERVIEW&symbol={selected_symbol}&apikey={api_key}'
        r_info = requests.get(url_info)
        info = r_info.json()

        if 'Time Series (5min)' in data:
            for date in data['Time Series (5min)']:
                if '1. open' in data['Time Series (5min)'][date]:
                    x.append(date)
                    y.append(data['Time Series (5min)'][date]['1. open'])
                else:
                    print("La clé '1. open' est absente dans la liste de data")
        else:
            print("La clé 'Time Series (5min)' est absente dans le dictionnaire")

        full_date = x[0][:10]
        full_date = datetime.strptime(full_date, '%Y-%m-%d')
        full_date = full_date.strftime("%A, %B %d, %Y")

        for i in range(len(x)):
            x[i] = x[i][11:]

        x.reverse()
        y.reverse()

        """formating y and x to float and datetime instead of strings"""
        y = list(map(float, y))
        x = [datetime.strptime(time_str, '%H:%M:%S') for time_str in x]

        fig, ax = plt.subplots()
        ax.plot(x, y)
        ax.set_xlabel('Time')
        ax.set_ylabel('Price')
        ax.set_title(f'{selected_symbol} Stock Exchange - {full_date}')

        """ Y AXE using np for showing only 4 """
        y_min, y_max = min(y), max(y)
        y_ticks = np.linspace(y_min, y_max, 4)
        ax.set_yticks(y_ticks)

        """ X AXE using mdate for showing every 120min """
        ax.xaxis.set_major_locator(mdates.MinuteLocator(interval=120))
        ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
        fig.autofmt_xdate()

        img = io.BytesIO()
        fig.savefig(img, format='png', bbox_inches='tight', pad_inches=0)
        img.seek(0)
        plot_url = base64.b64encode(img.getvalue()).decode()

        """ testing avec info_exemple mais à changer par la suite par info """
        if info :
            present_symbol = (f"<h4>{info['Symbol']} - {info['Name']} : </h4><br>"
                              f"{info["Description"]}<br>"
                              f"<span class='span_info'><i>{info["Country"]} - {info["Currency"]} - {info["Sector"]} <span></i>")


    return render_template('home.html',
                           data=data,
                           info=info,
                           symbols=symbols,
                           error=error,
                           x=x,
                           y=y,
                           plot_url=plot_url,
                           present_symbol=present_symbol)


if __name__ == '__main__':
    app.run()
